---
abstract: 'Jifty plugin to add a wiki toolbar to your textarea box'
author:
  - 'Yves Agostini, <yvesago@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.11
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Jifty-Plugin-WikiToolbar
no_index:
  directory:
    - inc
    - share
    - t
requires:
  Jifty: 0.70416
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
